# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://www.block-cast.de"
baseurl: "/"
siteIcon: /media/BlockCast.png
siteYear: 2024
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Block-Cast MC
serverDescription: Das offizielle Netzwerk vom  Podcast Blockcast.
serverIP: mc.block-cast.de
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/CjCrpFrZgk
discordServerID: 1204773459419205642
discordChannelID: 1204814923276746764


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
